server:
  port: 8080
  
spring:
  application:
    name: automobile
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5555/auth/user
      
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka